---  

- name: Route53 record name
  set_fact:
    route: "{{ inventory_hostname }}.{{ vpc }}.{{ aws_region }}.{{ hosted_zone }}"

- name: Route53 record
  route53:
    state: "{{ state }}"
    zone: "{{ hosted_zone }}"
    record: "{{ route }}"
    value: "{{ private_ip_address }}"
    type: A
    ttl: 7200
    private_zone: yes
    overwrite: yes
    wait: yes


- name: Update inventory with ip for ssh
  add_host:
    name: "{{ public_ip_address }}"
    groups: 
      - "{{ inventory_name }}_nodes"
      - "{{ subnet }}"
    route: "{{ route }}"
  when: state == 'present'  
