---

#provision variables
gluster_version: gluster4u0_centos7
ami_id: ami-f4d4b694
public_ip: yes
instance_type: t2.micro
security_groups:
  - vpc
  - allow-public-ssh

volumes:
  # this is root device in coreos  
  - device_name: /dev/xvda
    volume_size: 30
    volume_type: gp2
    delete_on_termination: true
cloud_config_template: gluster_cloud_config  